server:
  port: 8081

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vue03
  redis:
    port: 6379
    host: 127.0.0.1


mybatis-plus:
  type-aliases-package: com.jy.entity
  mapper-locations: classpath:com/jy/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted